// SPDX-License-Identifier: MPL-2.0
#pragma once

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(lcStore)
Q_DECLARE_LOGGING_CATEGORY(lcMime)
Q_DECLARE_LOGGING_CATEGORY(lcNet)
Q_DECLARE_LOGGING_CATEGORY(lcCrypto)
Q_DECLARE_LOGGING_CATEGORY(lcMail)
Q_DECLARE_LOGGING_CATEGORY(lcEngine)
